config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
 
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end 
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: :User
  belongs_to :post

  after_create :updatecommentscounter
  after_destroy :decrementcommentscounter

  def decrementcommentscounter
    post.decrement!(:commentscounter)
  end

  def updatecommentscounter
    post.increment!(:commentscounter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: :User
  belongs_to :post

  after_create :updatelikescounter

  def updatelikescounter
    post.increment!(:likescounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :commentscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likescounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: :User
  has_many :likes
  has_many :comments

  after_create :updatepostscounter

  def updatepostscounter
    author.increment!(:postscounter)
  end

  def recentfivecomments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
  validates :postscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id

  before_validation :assignpostscounter
  def assignpostscounter
    self.postscounter = posts.count
  end

  def recentthreeposts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :photo, :bio) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :photo, :bio, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
    @posts = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    @comments = Comment.find(params[:comment_id])

    respond_to do |format|
      format.html
      format.json { render json: @comments }
    end
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    @post = Post.find(params[:post_id])

    if @comment.save
      respond_to do |format|
        format.html { redirect_to user_post_path(@post.author, @post), notice: 'Comment created' }
        format.json { render json: @comment, status: :created }
      end

    else
      respond_to do |format|
        format.html { render :new, alert: 'Comment not created!' }
        format.json { render json: @comment.errors, status: :unprocessable_entry }
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment

    puts 'Authorization successful'

    if @comment.destroy
      flash[:success] = 'Comment deleted successfully.'
    else
      flash[:danger] = 'Comment could not be deleted.'
    end

    redirect_to user_posts_path(@post.author, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]

    if @like.save
      flash[:success] = 'Liked'
      redirect_to user_posts_path
    else
      render :create
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  skip_before_action :verify_authenticity_token
  def index
    @user = User.find(params[:user_id])
    @posts = Post.all

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.commentscounter = 0
    @post.likescounter = 0
    @post.author = current_user

    if @post.save

      redirect_to "/users/#{current_user.id}/posts", notice: 'Post created successfully!'
    else
      render :new, notice: 'Post could not be created.'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.comments.destroy_all
    @post.likes.destroy_all # delete all comments associated with the post
    @post.destroy # delete the post itself
    redirect_to user_posts_path(current_user), notice: 'Post deleted successfully.'
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find_by_id(params[:id])
    # @post = Post.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Create a Comment</h1>

<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>
 
  <%= form.label :text %>
  <%= form.text_area :text %>

  <%= form.submit 'Create Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
<div class="user_profile">
<div class="photos">
    <ul class="photo"> 
   <li> <img src=" <%= @user.photo %> " </li>
   </ul>
</div>
<div class="names_posts">
    <ul class="name_post"> 
   <li class="list_name"> <%= @user.name %> </li>
   <li class="list_countpost">Number of posts: <%= @user.postscounter %> </li>
   </ul>
</div>
 </div>

 <button class="page-btn">
        <%= link_to 'Create New Post', new_user_post_path(@user), style: 'color: black; text-decoration: none;' %>
 </button>

 <div class="page-description">
    <h3> List of previous Posts and respective comments:</h3>
 </div>

 <div class="post">
      <% @posts.includes(:comments, :author).each do |post| %>
    <ul class="post_info width"> 
    <h3 class="title"><%= link_to post.title, user_post_path(@user, post)%> #<%= post.id%></h3>
   <li class="bio_content"> <%= post.text %> </li>
   <li class="list_countcomentlikes">Comments: <%= post.commentscounter %>, Likes: <%= post.likescounter %> </li>
   </ul>
   <div class="post_comment">
   <% post.recentfivecomments.includes(:author).each do |comment| %>
      <ul class="comment width"> 
          <li> <%= comment.author.name %>: <%= comment.text%> </li>
       </ul>
       <% end %> 
   </div>
   <% end %>
  </div>
  <button type:submit class="all-posts">Pagination</buttom>
</div>

app/views/posts/new.html.erb
<h1>Create a post</h1>

<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :text %>
  <%= form.text_area :text %>
  <%= form.submit 'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<div class="container">

 <div class="post">
    <ul class="post_info width"> 
    <div class="header">
    <h3 class="title"><%= @post.title%> #<%= @post.id%> by <%= @post.author.name%></h3>
    <li class="countcomentlikes">Comments: <%= @post.commentscounter %>, Likes: <%= @post.likescounter %> </li>
    </div>
   <li class="bio_content"> <%= @post.text %> </li>
   </ul>
   <button class="page-btn">
        <%= link_to 'Create New Comment', new_user_post_comment_path(@post.author, @post), style: 'color: black; text-decoration: none;' %>
    </button>
    <div class="general-btn">
      <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |form| %>
        <%= form.submit 'Like Post' %>
      <% end %>
   <button class="btn btn-danger"> <%= link_to 'Delete Post',user_post_path(@post.author, @post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> </button>
    </div>
   
    <div class="comment">
    <% @post.comments.each do |comment| %>
    <div class="coment-container">
   <p><%= comment.author.name %>-</p>
   <p> <%= comment.text %> </p>
   </div>
   <button class: 'btn btn-danger'> <%= link_to 'Delete Comment',user_post_comment_path(@post.author, @post, comment), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> </button>
 <% end %>
 </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<div class="container">
<div class="user_profile">
<div class="photos">
  <% @users.each do |user| %>
    <ul class="photo"> 
   <li> <img src="<%= user.photo %>"> </li>
   </ul>
    <% end %>
</div>

<div class="names_posts">
  <% @users.each do |user| %>
    <ul class="name_post"> 
   <li class="list_name"> <%= link_to user.name, user_path(user) %> </li>
   <li class="list_countpost">Number of posts: <%= user.postscounter %> </li>
   </ul>
    <% end %>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="user_profile">
<div class="photos">
    <ul class="photo"> 
   <li> <img src="<%= @user.photo %>"> </li>
   </ul>
</div>
<div class="names_posts">
    <ul class="name_post"> 
   <li class="list_name"> <%= @user.name %> </li>
   <li class="list_countpost">Number of post: <%= @user.postscounter %> </li>
   </ul>
</div>
</div>
<div class="bio">
    <ul class="bio_info width"> 
    <h3 class="title">Bio</h3>
   <li class="bio_content"> <%= @user.bio %> </li>
   </ul>
</div>
<div class="post">
<% @user.recentthreeposts.each do |post| %>
    <ul class="post_info width"> 
    <h3 class="title"><%= link_to post.title, user_post_path(@user, post) %> #<%= post.id%></h3>
   <li class="bio_content"> <%= post.text %> </li>
   <li class="list_countcomentlikes">Comments: <%= post.commentscounter %>, Likes: <%= post.likescounter %> </li>
   </ul>
<% end %>
</div>
<button class="allpost"> <%= link_to 'See all Posts', user_posts_path(@user.id) %> </button>
</div>